---
title: "Nawqa_map_2019_11_01"
output: html_document
editor_options: 
  chunk_output_type: console
---

# load packages
```{r}

library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)

```

# create map
```{r}
names(dat)

usa=map_data('usa')
states=map_data('state')
head(states)

us_base=ggplot(data=usa,mapping=aes(x=long,y=lat,group=group))+coord_fixed(1.3)+geom_polygon(color="black",fill="white")
us_base

ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
)

us_base+geom_polygon(data=states,color=alpha("gray",0.5),fill="white")+geom_point(data=dat,aes(x=longitude,y=latitude,group=stationId),size=0.1)+ditch_the_axes

us_base+geom_polygon(data=states,color=alpha("gray",0.5),fill="white")+geom_point(data=dat,aes(x=longitude,y=latitude,group=stationId,color=log10(DIP_mc)),size=0.5)+scale_color_gradient(low="yellow",high="red",name="DIP (mg/L)",breaks=c(-2,-1,0),labels=c("0.01","0.1","1"))+ditch_the_axes+theme_classic()

us_base+geom_polygon(data=states,color=alpha("gray",0.5),fill="white")+geom_point(data=dat,aes(x=longitude,y=latitude,group=stationId,color=log10(TN_mc)),size=0.5)+scale_color_gradient(low="yellow",high="red",name="TN (mg/L)",breaks=c(-1,0,1),labels=c("0.1","1","10"))+ditch_the_axes+theme_classic()

us_base+geom_polygon(data=states,color=alpha("gray",0.5),fill="white")+geom_point(data=dat,aes(x=longitude,y=latitude,group=stationId,color=log10(TP_mc)),size=0.5)+scale_color_gradient(low="yellow",high="red",name="TP (mg/L)",breaks=c(-2,-1,0),labels=c("0.01","0.1","1"))+ditch_the_axes+theme_classic()

us_base+geom_polygon(data=states,color=alpha("gray",0.5),fill="white")+geom_point(data=dat,aes(x=longitude,y=latitude,group=stationId,color=log10(samp_PNcorr)),size=0.5)+scale_color_gradient(low="yellow",high="red",name="PN (mg/L)",breaks=c(-3,-2,-1),labels=c("0.001","0.01","0.1"))+ditch_the_axes+theme_classic()

us_base+geom_polygon(data=states,color=alpha("gray",0.5),fill="white")+geom_point(data=dat,aes(x=longitude,y=latitude,group=stationId,color=log10(samp_PPcorr)),size=0.5)+scale_color_gradient(low="yellow",high="red",name="PP (mg/L)",breaks=c(-2,-1,0),labels=c("0.01","0.1","1"))+ditch_the_axes+theme_classic()

```

