---
title: "quantile_LOESS"
author: "David"
date: "11/21/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Quantile Loess code from https://www.r-statistics.com/2010/04/quantile-loess-combining-a-moving-quantile-window-with-loess-r-function/ written by Tal Galili
```{r}
# This code relies on the rollapply function from the "zoo" package.  My thanks goes to Achim Zeileis and Gabor Grothendieck for their work on the package.
Quantile.loess<- function(Y, X = NULL,
							number.of.splits = NULL,
							window.size = 20,
							percent.of.overlap.between.two.windows = NULL,
							the.distance.between.each.window = NULL,
							the.quant = .95,
							window.alignment = c("center"),
							window.function = function(x) {quantile(x, the.quant)},
							# If you wish to use this with a running average instead of a running quantile, you could simply use:
							# window.function = mean,
							...)
{
	# input: Y and X, and smothing parameters
	# output: new y and x
 
	# Extra parameter "..." goes to the loess
 
	# window.size ==  the number of observation in the window (not the window length!)
 
	# "number.of.splits" will override "window.size"
	# let's compute the window.size:
	if(!is.null(number.of.splits)) {window.size <- ceiling(length(Y)/number.of.splits)}
 
	# If the.distance.between.each.window is not specified, let's make the distances fully distinct
	if(is.null(the.distance.between.each.window)) {the.distance.between.each.window <- window.size}
 
	# If percent.of.overlap.between.windows is not null, it will override the.distance.between.each.window
	if(!is.null(percent.of.overlap.between.two.windows))
		{
			the.distance.between.each.window <- window.size * (1-percent.of.overlap.between.two.windows)
		}
 
 
 
	# loading zoo
	if(!require(zoo))
	{
		print("zoo is not installed - please install it.")
		install.packages("zoo")
	}
 
 
	if(is.null(X)) {X <- index(Y)} # if we don't have any X, then Y must be ordered, in which case, we can use the indexes of Y as X.
 
	# creating our new X and Y
	zoo.Y <- zoo(x = Y, order.by = X)
	#zoo.X <- attributes(zoo.Y)$index
 
	new.Y <- rollapply(zoo.Y, width = window.size,
								FUN = window.function,
								by = the.distance.between.each.window,
								align = window.alignment)
	new.X <- attributes(new.Y)$index
	new.Y.loess <- loess(new.Y~new.X, family = "sym",...)$fitted
 
	return(list(y = new.Y, x = new.X, y.loess = new.Y.loess))
}
```

# load nawqa data
```{r}

concs=data.frame(DIN_mc,TN_TP$TN,med_PNcorr,DIN_SRP_MC$SRP_mc,TN_TP$TP,med_PPcorr,pURB,pAG,pUND)
colnames(concs)=c("DIN","TN","PN","SRP","TP","PP","pAG","pURB","pFOR")
write.csv(concs,file="/Users/dmanning/Documents/NAWQA_concs_summary.csv")

concs=read.csv("/Users/dmanning/Documents/NAWQA_concs_summary.csv")

```

# create quantile loess plots, starting with DIN vs. AG
```{r}

X.ag=jitter(concs$pAG) # if multiple values for same x, then x must be jittered
Y.din=concs$DIN # din concentrations

### example quantile loess code from TG R blog post #####
QL <- Quantile.loess(Y = Ozone.2, X = Temp.2,
							the.quant = .95,
							window.size = 10,
							window.alignment = c("center"))
points(QL$y.loess ~ QL$x, type = "l", col = "green")
### --------------------------- ###

# 10-90th percentile of DIN
QL.DIN.AG.10=Quantile.loess(Y=Y.din,X=X.ag,the.quant=0.1,window.size=10,window.alignment=c("center"))
QL.DIN.AG.25=Quantile.loess(Y=Y.din,X=X.ag,the.quant=0.25,window.size=10,window.alignment=c("center"))
QL.DIN.AG.50=Quantile.loess(Y=Y.din,X=X.ag,the.quant=0.50,window.size=10,window.alignment=c("center"))
QL.DIN.AG.75=Quantile.loess(Y=Y.din,X=X.ag,the.quant=0.75,window.size=10,window.alignment=c("center"))
QL.DIN.AG.90=Quantile.loess(Y=Y.din,X=X.ag,the.quant=0.90,window.size=10,window.alignment=c("center"))

plot(DIN~pAG,data=concs,col="gray",cex=0.1,cex.lab=1.5,cex.axis=1.5,ylab="DIN (mg/L)",xlab="proportion agriculture")
#axis(side=2,at=c(-2,-1,0,1),labels=c(expression(10^-2),expression(10^-1),expression(10^0),expression(10^1)),cex.axis=1.5)
points(QL.DIN.AG.10$y.loess~QL.DIN.AG.10$x,type="l")
points(QL.DIN.AG.25$y.loess~QL.DIN.AG.25$x,type="l")
points(QL.DIN.AG.50$y.loess~QL.DIN.AG.25$x,type="l")
points(QL.DIN.AG.75$y.loess~QL.DIN.AG.25$x,type="l")
points(QL.DIN.AG.90$y.loess~QL.DIN.AG.90$x,type="l")
#text(0.91,-0.25,"10%")
#text(0.91,0,"25%")
#text(0.91,0.2,"50%")
#text(0.91,0.4,"75%")
#text(0.91,0.6,"90%")
```



